/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author javie
 */
public class tablero extends javax.swing.JFrame {

    /**
     * Creates new form tablero
     */
    public tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana = new javax.swing.JPanel();
        bordederecho = new javax.swing.JPanel();
        bordeinferior = new javax.swing.JPanel();
        bordesuperior = new javax.swing.JPanel();
        huecoIzq = new javax.swing.JLabel();
        LabelA = new javax.swing.JLabel();
        LabelB = new javax.swing.JLabel();
        LabelC = new javax.swing.JLabel();
        LabelD = new javax.swing.JLabel();
        LabelE = new javax.swing.JLabel();
        LabelF = new javax.swing.JLabel();
        LabelG = new javax.swing.JLabel();
        LabelH = new javax.swing.JLabel();
        HuecoDer = new javax.swing.JLabel();
        bordeizquierdo = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        tablero = new javax.swing.JPanel();
        primerafila = new javax.swing.JPanel();
        primeracol = new javax.swing.JPanel();
        segundacol = new javax.swing.JPanel();
        tercercol = new javax.swing.JPanel();
        cuartacol = new javax.swing.JPanel();
        quintacol = new javax.swing.JPanel();
        sextacol = new javax.swing.JPanel();
        septimacol = new javax.swing.JPanel();
        octavacol = new javax.swing.JPanel();
        segundafila = new javax.swing.JPanel();
        primeracol1 = new javax.swing.JPanel();
        segundacol1 = new javax.swing.JPanel();
        tercercol1 = new javax.swing.JPanel();
        cuartacol1 = new javax.swing.JPanel();
        quintacol1 = new javax.swing.JPanel();
        sextacol1 = new javax.swing.JPanel();
        septimacol1 = new javax.swing.JPanel();
        octavacol1 = new javax.swing.JPanel();
        primerafila1 = new javax.swing.JPanel();
        primeracol2 = new javax.swing.JPanel();
        segundacol2 = new javax.swing.JPanel();
        tercercol2 = new javax.swing.JPanel();
        cuartacol2 = new javax.swing.JPanel();
        quintacol2 = new javax.swing.JPanel();
        sextacol2 = new javax.swing.JPanel();
        septimacol2 = new javax.swing.JPanel();
        octavacol2 = new javax.swing.JPanel();
        segundafila1 = new javax.swing.JPanel();
        primeracol3 = new javax.swing.JPanel();
        segundacol3 = new javax.swing.JPanel();
        tercercol3 = new javax.swing.JPanel();
        cuartacol3 = new javax.swing.JPanel();
        quintacol3 = new javax.swing.JPanel();
        sextacol3 = new javax.swing.JPanel();
        septimacol3 = new javax.swing.JPanel();
        octavacol3 = new javax.swing.JPanel();
        primerafila2 = new javax.swing.JPanel();
        primeracol4 = new javax.swing.JPanel();
        segundacol4 = new javax.swing.JPanel();
        tercercol4 = new javax.swing.JPanel();
        cuartacol4 = new javax.swing.JPanel();
        quintacol4 = new javax.swing.JPanel();
        sextacol4 = new javax.swing.JPanel();
        septimacol4 = new javax.swing.JPanel();
        octavacol4 = new javax.swing.JPanel();
        segundafila2 = new javax.swing.JPanel();
        primeracol5 = new javax.swing.JPanel();
        segundacol5 = new javax.swing.JPanel();
        tercercol5 = new javax.swing.JPanel();
        cuartacol5 = new javax.swing.JPanel();
        quintacol5 = new javax.swing.JPanel();
        sextacol5 = new javax.swing.JPanel();
        septimacol5 = new javax.swing.JPanel();
        octavacol5 = new javax.swing.JPanel();
        primerafila3 = new javax.swing.JPanel();
        primeracol6 = new javax.swing.JPanel();
        segundacol6 = new javax.swing.JPanel();
        tercercol6 = new javax.swing.JPanel();
        cuartacol6 = new javax.swing.JPanel();
        quintacol6 = new javax.swing.JPanel();
        sextacol6 = new javax.swing.JPanel();
        septimacol6 = new javax.swing.JPanel();
        octavacol6 = new javax.swing.JPanel();
        segundafila3 = new javax.swing.JPanel();
        primeracol7 = new javax.swing.JPanel();
        segundacol7 = new javax.swing.JPanel();
        tercercol7 = new javax.swing.JPanel();
        cuartacol7 = new javax.swing.JPanel();
        quintacol7 = new javax.swing.JPanel();
        sextacol7 = new javax.swing.JPanel();
        septimacol7 = new javax.swing.JPanel();
        octavacol7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        ventana.setMinimumSize(new java.awt.Dimension(600, 600));
        ventana.setPreferredSize(new java.awt.Dimension(600, 600));
        ventana.setLayout(new java.awt.BorderLayout());

        bordederecho.setPreferredSize(new java.awt.Dimension(50, 450));

        javax.swing.GroupLayout bordederechoLayout = new javax.swing.GroupLayout(bordederecho);
        bordederecho.setLayout(bordederechoLayout);
        bordederechoLayout.setHorizontalGroup(
            bordederechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        bordederechoLayout.setVerticalGroup(
            bordederechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        ventana.add(bordederecho, java.awt.BorderLayout.LINE_END);

        bordeinferior.setPreferredSize(new java.awt.Dimension(500, 50));

        javax.swing.GroupLayout bordeinferiorLayout = new javax.swing.GroupLayout(bordeinferior);
        bordeinferior.setLayout(bordeinferiorLayout);
        bordeinferiorLayout.setHorizontalGroup(
            bordeinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        bordeinferiorLayout.setVerticalGroup(
            bordeinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ventana.add(bordeinferior, java.awt.BorderLayout.PAGE_END);

        bordesuperior.setPreferredSize(new java.awt.Dimension(500, 50));
        bordesuperior.setLayout(new java.awt.GridLayout());
        bordesuperior.add(huecoIzq);

        LabelA.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA.setText("A");
        LabelA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelA);

        LabelB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelB.setText("B");
        LabelB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelB);

        LabelC.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelC.setText("C");
        LabelC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelC);

        LabelD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelD.setText("D");
        LabelD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelD);

        LabelE.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelE.setText("E");
        LabelE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelE);

        LabelF.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelF.setText("F");
        LabelF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelF);

        LabelG.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelG.setText("G");
        LabelG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelG);

        LabelH.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelH.setText("H");
        LabelH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bordesuperior.add(LabelH);
        bordesuperior.add(HuecoDer);

        ventana.add(bordesuperior, java.awt.BorderLayout.PAGE_START);

        bordeizquierdo.setPreferredSize(new java.awt.Dimension(50, 450));
        bordeizquierdo.setLayout(new java.awt.GridLayout(8, 1));

        Label1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("1");
        bordeizquierdo.add(Label1);

        Label2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label2.setText("2");
        bordeizquierdo.add(Label2);

        Label3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label3.setText("3");
        bordeizquierdo.add(Label3);

        Label4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label4.setText("4");
        bordeizquierdo.add(Label4);

        Label5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label5.setText("5");
        bordeizquierdo.add(Label5);

        Label6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label6.setText("6");
        bordeizquierdo.add(Label6);

        Label7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label7.setText("7");
        bordeizquierdo.add(Label7);

        Label8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label8.setText("8");
        bordeizquierdo.add(Label8);

        ventana.add(bordeizquierdo, java.awt.BorderLayout.LINE_START);

        tablero.setLayout(new java.awt.GridLayout(8, 1));

        primerafila.setLayout(new java.awt.GridLayout(1, 8));

        primeracol.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout primeracolLayout = new javax.swing.GroupLayout(primeracol);
        primeracol.setLayout(primeracolLayout);
        primeracolLayout.setHorizontalGroup(
            primeracolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracolLayout.setVerticalGroup(
            primeracolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(primeracol);

        segundacol.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout segundacolLayout = new javax.swing.GroupLayout(segundacol);
        segundacol.setLayout(segundacolLayout);
        segundacolLayout.setHorizontalGroup(
            segundacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacolLayout.setVerticalGroup(
            segundacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(segundacol);

        tercercol.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tercercolLayout = new javax.swing.GroupLayout(tercercol);
        tercercol.setLayout(tercercolLayout);
        tercercolLayout.setHorizontalGroup(
            tercercolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercolLayout.setVerticalGroup(
            tercercolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(tercercol);

        cuartacol.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cuartacolLayout = new javax.swing.GroupLayout(cuartacol);
        cuartacol.setLayout(cuartacolLayout);
        cuartacolLayout.setHorizontalGroup(
            cuartacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacolLayout.setVerticalGroup(
            cuartacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(cuartacol);

        quintacol.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quintacolLayout = new javax.swing.GroupLayout(quintacol);
        quintacol.setLayout(quintacolLayout);
        quintacolLayout.setHorizontalGroup(
            quintacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacolLayout.setVerticalGroup(
            quintacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(quintacol);

        sextacol.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout sextacolLayout = new javax.swing.GroupLayout(sextacol);
        sextacol.setLayout(sextacolLayout);
        sextacolLayout.setHorizontalGroup(
            sextacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacolLayout.setVerticalGroup(
            sextacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(sextacol);

        septimacol.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout septimacolLayout = new javax.swing.GroupLayout(septimacol);
        septimacol.setLayout(septimacolLayout);
        septimacolLayout.setHorizontalGroup(
            septimacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacolLayout.setVerticalGroup(
            septimacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(septimacol);

        octavacol.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout octavacolLayout = new javax.swing.GroupLayout(octavacol);
        octavacol.setLayout(octavacolLayout);
        octavacolLayout.setHorizontalGroup(
            octavacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacolLayout.setVerticalGroup(
            octavacolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila.add(octavacol);

        tablero.add(primerafila);

        segundafila.setLayout(new java.awt.GridLayout(1, 8));

        primeracol1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout primeracol1Layout = new javax.swing.GroupLayout(primeracol1);
        primeracol1.setLayout(primeracol1Layout);
        primeracol1Layout.setHorizontalGroup(
            primeracol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracol1Layout.setVerticalGroup(
            primeracol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(primeracol1);

        segundacol1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout segundacol1Layout = new javax.swing.GroupLayout(segundacol1);
        segundacol1.setLayout(segundacol1Layout);
        segundacol1Layout.setHorizontalGroup(
            segundacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacol1Layout.setVerticalGroup(
            segundacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(segundacol1);

        tercercol1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout tercercol1Layout = new javax.swing.GroupLayout(tercercol1);
        tercercol1.setLayout(tercercol1Layout);
        tercercol1Layout.setHorizontalGroup(
            tercercol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercol1Layout.setVerticalGroup(
            tercercol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(tercercol1);

        cuartacol1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cuartacol1Layout = new javax.swing.GroupLayout(cuartacol1);
        cuartacol1.setLayout(cuartacol1Layout);
        cuartacol1Layout.setHorizontalGroup(
            cuartacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacol1Layout.setVerticalGroup(
            cuartacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(cuartacol1);

        quintacol1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout quintacol1Layout = new javax.swing.GroupLayout(quintacol1);
        quintacol1.setLayout(quintacol1Layout);
        quintacol1Layout.setHorizontalGroup(
            quintacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacol1Layout.setVerticalGroup(
            quintacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(quintacol1);

        sextacol1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sextacol1Layout = new javax.swing.GroupLayout(sextacol1);
        sextacol1.setLayout(sextacol1Layout);
        sextacol1Layout.setHorizontalGroup(
            sextacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacol1Layout.setVerticalGroup(
            sextacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(sextacol1);

        septimacol1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout septimacol1Layout = new javax.swing.GroupLayout(septimacol1);
        septimacol1.setLayout(septimacol1Layout);
        septimacol1Layout.setHorizontalGroup(
            septimacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacol1Layout.setVerticalGroup(
            septimacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(septimacol1);

        octavacol1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout octavacol1Layout = new javax.swing.GroupLayout(octavacol1);
        octavacol1.setLayout(octavacol1Layout);
        octavacol1Layout.setHorizontalGroup(
            octavacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacol1Layout.setVerticalGroup(
            octavacol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila.add(octavacol1);

        tablero.add(segundafila);

        primerafila1.setLayout(new java.awt.GridLayout(1, 8));

        primeracol2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout primeracol2Layout = new javax.swing.GroupLayout(primeracol2);
        primeracol2.setLayout(primeracol2Layout);
        primeracol2Layout.setHorizontalGroup(
            primeracol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracol2Layout.setVerticalGroup(
            primeracol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(primeracol2);

        segundacol2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout segundacol2Layout = new javax.swing.GroupLayout(segundacol2);
        segundacol2.setLayout(segundacol2Layout);
        segundacol2Layout.setHorizontalGroup(
            segundacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacol2Layout.setVerticalGroup(
            segundacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(segundacol2);

        tercercol2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tercercol2Layout = new javax.swing.GroupLayout(tercercol2);
        tercercol2.setLayout(tercercol2Layout);
        tercercol2Layout.setHorizontalGroup(
            tercercol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercol2Layout.setVerticalGroup(
            tercercol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(tercercol2);

        cuartacol2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cuartacol2Layout = new javax.swing.GroupLayout(cuartacol2);
        cuartacol2.setLayout(cuartacol2Layout);
        cuartacol2Layout.setHorizontalGroup(
            cuartacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacol2Layout.setVerticalGroup(
            cuartacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(cuartacol2);

        quintacol2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quintacol2Layout = new javax.swing.GroupLayout(quintacol2);
        quintacol2.setLayout(quintacol2Layout);
        quintacol2Layout.setHorizontalGroup(
            quintacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacol2Layout.setVerticalGroup(
            quintacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(quintacol2);

        sextacol2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout sextacol2Layout = new javax.swing.GroupLayout(sextacol2);
        sextacol2.setLayout(sextacol2Layout);
        sextacol2Layout.setHorizontalGroup(
            sextacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacol2Layout.setVerticalGroup(
            sextacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(sextacol2);

        septimacol2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout septimacol2Layout = new javax.swing.GroupLayout(septimacol2);
        septimacol2.setLayout(septimacol2Layout);
        septimacol2Layout.setHorizontalGroup(
            septimacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacol2Layout.setVerticalGroup(
            septimacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(septimacol2);

        octavacol2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout octavacol2Layout = new javax.swing.GroupLayout(octavacol2);
        octavacol2.setLayout(octavacol2Layout);
        octavacol2Layout.setHorizontalGroup(
            octavacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacol2Layout.setVerticalGroup(
            octavacol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila1.add(octavacol2);

        tablero.add(primerafila1);

        segundafila1.setLayout(new java.awt.GridLayout(1, 8));

        primeracol3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout primeracol3Layout = new javax.swing.GroupLayout(primeracol3);
        primeracol3.setLayout(primeracol3Layout);
        primeracol3Layout.setHorizontalGroup(
            primeracol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracol3Layout.setVerticalGroup(
            primeracol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(primeracol3);

        segundacol3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout segundacol3Layout = new javax.swing.GroupLayout(segundacol3);
        segundacol3.setLayout(segundacol3Layout);
        segundacol3Layout.setHorizontalGroup(
            segundacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacol3Layout.setVerticalGroup(
            segundacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(segundacol3);

        tercercol3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout tercercol3Layout = new javax.swing.GroupLayout(tercercol3);
        tercercol3.setLayout(tercercol3Layout);
        tercercol3Layout.setHorizontalGroup(
            tercercol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercol3Layout.setVerticalGroup(
            tercercol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(tercercol3);

        cuartacol3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cuartacol3Layout = new javax.swing.GroupLayout(cuartacol3);
        cuartacol3.setLayout(cuartacol3Layout);
        cuartacol3Layout.setHorizontalGroup(
            cuartacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacol3Layout.setVerticalGroup(
            cuartacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(cuartacol3);

        quintacol3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout quintacol3Layout = new javax.swing.GroupLayout(quintacol3);
        quintacol3.setLayout(quintacol3Layout);
        quintacol3Layout.setHorizontalGroup(
            quintacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacol3Layout.setVerticalGroup(
            quintacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(quintacol3);

        sextacol3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sextacol3Layout = new javax.swing.GroupLayout(sextacol3);
        sextacol3.setLayout(sextacol3Layout);
        sextacol3Layout.setHorizontalGroup(
            sextacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacol3Layout.setVerticalGroup(
            sextacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(sextacol3);

        septimacol3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout septimacol3Layout = new javax.swing.GroupLayout(septimacol3);
        septimacol3.setLayout(septimacol3Layout);
        septimacol3Layout.setHorizontalGroup(
            septimacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacol3Layout.setVerticalGroup(
            septimacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(septimacol3);

        octavacol3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout octavacol3Layout = new javax.swing.GroupLayout(octavacol3);
        octavacol3.setLayout(octavacol3Layout);
        octavacol3Layout.setHorizontalGroup(
            octavacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacol3Layout.setVerticalGroup(
            octavacol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila1.add(octavacol3);

        tablero.add(segundafila1);

        primerafila2.setLayout(new java.awt.GridLayout(1, 8));

        primeracol4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout primeracol4Layout = new javax.swing.GroupLayout(primeracol4);
        primeracol4.setLayout(primeracol4Layout);
        primeracol4Layout.setHorizontalGroup(
            primeracol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracol4Layout.setVerticalGroup(
            primeracol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(primeracol4);

        segundacol4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout segundacol4Layout = new javax.swing.GroupLayout(segundacol4);
        segundacol4.setLayout(segundacol4Layout);
        segundacol4Layout.setHorizontalGroup(
            segundacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacol4Layout.setVerticalGroup(
            segundacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(segundacol4);

        tercercol4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tercercol4Layout = new javax.swing.GroupLayout(tercercol4);
        tercercol4.setLayout(tercercol4Layout);
        tercercol4Layout.setHorizontalGroup(
            tercercol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercol4Layout.setVerticalGroup(
            tercercol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(tercercol4);

        cuartacol4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cuartacol4Layout = new javax.swing.GroupLayout(cuartacol4);
        cuartacol4.setLayout(cuartacol4Layout);
        cuartacol4Layout.setHorizontalGroup(
            cuartacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacol4Layout.setVerticalGroup(
            cuartacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(cuartacol4);

        quintacol4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quintacol4Layout = new javax.swing.GroupLayout(quintacol4);
        quintacol4.setLayout(quintacol4Layout);
        quintacol4Layout.setHorizontalGroup(
            quintacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacol4Layout.setVerticalGroup(
            quintacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(quintacol4);

        sextacol4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout sextacol4Layout = new javax.swing.GroupLayout(sextacol4);
        sextacol4.setLayout(sextacol4Layout);
        sextacol4Layout.setHorizontalGroup(
            sextacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacol4Layout.setVerticalGroup(
            sextacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(sextacol4);

        septimacol4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout septimacol4Layout = new javax.swing.GroupLayout(septimacol4);
        septimacol4.setLayout(septimacol4Layout);
        septimacol4Layout.setHorizontalGroup(
            septimacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacol4Layout.setVerticalGroup(
            septimacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(septimacol4);

        octavacol4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout octavacol4Layout = new javax.swing.GroupLayout(octavacol4);
        octavacol4.setLayout(octavacol4Layout);
        octavacol4Layout.setHorizontalGroup(
            octavacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacol4Layout.setVerticalGroup(
            octavacol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila2.add(octavacol4);

        tablero.add(primerafila2);

        segundafila2.setLayout(new java.awt.GridLayout(1, 8));

        primeracol5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout primeracol5Layout = new javax.swing.GroupLayout(primeracol5);
        primeracol5.setLayout(primeracol5Layout);
        primeracol5Layout.setHorizontalGroup(
            primeracol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracol5Layout.setVerticalGroup(
            primeracol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(primeracol5);

        segundacol5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout segundacol5Layout = new javax.swing.GroupLayout(segundacol5);
        segundacol5.setLayout(segundacol5Layout);
        segundacol5Layout.setHorizontalGroup(
            segundacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacol5Layout.setVerticalGroup(
            segundacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(segundacol5);

        tercercol5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout tercercol5Layout = new javax.swing.GroupLayout(tercercol5);
        tercercol5.setLayout(tercercol5Layout);
        tercercol5Layout.setHorizontalGroup(
            tercercol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercol5Layout.setVerticalGroup(
            tercercol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(tercercol5);

        cuartacol5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cuartacol5Layout = new javax.swing.GroupLayout(cuartacol5);
        cuartacol5.setLayout(cuartacol5Layout);
        cuartacol5Layout.setHorizontalGroup(
            cuartacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacol5Layout.setVerticalGroup(
            cuartacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(cuartacol5);

        quintacol5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout quintacol5Layout = new javax.swing.GroupLayout(quintacol5);
        quintacol5.setLayout(quintacol5Layout);
        quintacol5Layout.setHorizontalGroup(
            quintacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacol5Layout.setVerticalGroup(
            quintacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(quintacol5);

        sextacol5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sextacol5Layout = new javax.swing.GroupLayout(sextacol5);
        sextacol5.setLayout(sextacol5Layout);
        sextacol5Layout.setHorizontalGroup(
            sextacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacol5Layout.setVerticalGroup(
            sextacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(sextacol5);

        septimacol5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout septimacol5Layout = new javax.swing.GroupLayout(septimacol5);
        septimacol5.setLayout(septimacol5Layout);
        septimacol5Layout.setHorizontalGroup(
            septimacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacol5Layout.setVerticalGroup(
            septimacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(septimacol5);

        octavacol5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout octavacol5Layout = new javax.swing.GroupLayout(octavacol5);
        octavacol5.setLayout(octavacol5Layout);
        octavacol5Layout.setHorizontalGroup(
            octavacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacol5Layout.setVerticalGroup(
            octavacol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila2.add(octavacol5);

        tablero.add(segundafila2);

        primerafila3.setLayout(new java.awt.GridLayout(1, 8));

        primeracol6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout primeracol6Layout = new javax.swing.GroupLayout(primeracol6);
        primeracol6.setLayout(primeracol6Layout);
        primeracol6Layout.setHorizontalGroup(
            primeracol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracol6Layout.setVerticalGroup(
            primeracol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(primeracol6);

        segundacol6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout segundacol6Layout = new javax.swing.GroupLayout(segundacol6);
        segundacol6.setLayout(segundacol6Layout);
        segundacol6Layout.setHorizontalGroup(
            segundacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacol6Layout.setVerticalGroup(
            segundacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(segundacol6);

        tercercol6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tercercol6Layout = new javax.swing.GroupLayout(tercercol6);
        tercercol6.setLayout(tercercol6Layout);
        tercercol6Layout.setHorizontalGroup(
            tercercol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercol6Layout.setVerticalGroup(
            tercercol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(tercercol6);

        cuartacol6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout cuartacol6Layout = new javax.swing.GroupLayout(cuartacol6);
        cuartacol6.setLayout(cuartacol6Layout);
        cuartacol6Layout.setHorizontalGroup(
            cuartacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacol6Layout.setVerticalGroup(
            cuartacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(cuartacol6);

        quintacol6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quintacol6Layout = new javax.swing.GroupLayout(quintacol6);
        quintacol6.setLayout(quintacol6Layout);
        quintacol6Layout.setHorizontalGroup(
            quintacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacol6Layout.setVerticalGroup(
            quintacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(quintacol6);

        sextacol6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout sextacol6Layout = new javax.swing.GroupLayout(sextacol6);
        sextacol6.setLayout(sextacol6Layout);
        sextacol6Layout.setHorizontalGroup(
            sextacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacol6Layout.setVerticalGroup(
            sextacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(sextacol6);

        septimacol6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout septimacol6Layout = new javax.swing.GroupLayout(septimacol6);
        septimacol6.setLayout(septimacol6Layout);
        septimacol6Layout.setHorizontalGroup(
            septimacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacol6Layout.setVerticalGroup(
            septimacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(septimacol6);

        octavacol6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout octavacol6Layout = new javax.swing.GroupLayout(octavacol6);
        octavacol6.setLayout(octavacol6Layout);
        octavacol6Layout.setHorizontalGroup(
            octavacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacol6Layout.setVerticalGroup(
            octavacol6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        primerafila3.add(octavacol6);

        tablero.add(primerafila3);

        segundafila3.setLayout(new java.awt.GridLayout(1, 8));

        primeracol7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout primeracol7Layout = new javax.swing.GroupLayout(primeracol7);
        primeracol7.setLayout(primeracol7Layout);
        primeracol7Layout.setHorizontalGroup(
            primeracol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        primeracol7Layout.setVerticalGroup(
            primeracol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(primeracol7);

        segundacol7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout segundacol7Layout = new javax.swing.GroupLayout(segundacol7);
        segundacol7.setLayout(segundacol7Layout);
        segundacol7Layout.setHorizontalGroup(
            segundacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        segundacol7Layout.setVerticalGroup(
            segundacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(segundacol7);

        tercercol7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout tercercol7Layout = new javax.swing.GroupLayout(tercercol7);
        tercercol7.setLayout(tercercol7Layout);
        tercercol7Layout.setHorizontalGroup(
            tercercol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        tercercol7Layout.setVerticalGroup(
            tercercol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(tercercol7);

        cuartacol7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cuartacol7Layout = new javax.swing.GroupLayout(cuartacol7);
        cuartacol7.setLayout(cuartacol7Layout);
        cuartacol7Layout.setHorizontalGroup(
            cuartacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        cuartacol7Layout.setVerticalGroup(
            cuartacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(cuartacol7);

        quintacol7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout quintacol7Layout = new javax.swing.GroupLayout(quintacol7);
        quintacol7.setLayout(quintacol7Layout);
        quintacol7Layout.setHorizontalGroup(
            quintacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        quintacol7Layout.setVerticalGroup(
            quintacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(quintacol7);

        sextacol7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sextacol7Layout = new javax.swing.GroupLayout(sextacol7);
        sextacol7.setLayout(sextacol7Layout);
        sextacol7Layout.setHorizontalGroup(
            sextacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        sextacol7Layout.setVerticalGroup(
            sextacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(sextacol7);

        septimacol7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout septimacol7Layout = new javax.swing.GroupLayout(septimacol7);
        septimacol7.setLayout(septimacol7Layout);
        septimacol7Layout.setHorizontalGroup(
            septimacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        septimacol7Layout.setVerticalGroup(
            septimacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(septimacol7);

        octavacol7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout octavacol7Layout = new javax.swing.GroupLayout(octavacol7);
        octavacol7.setLayout(octavacol7Layout);
        octavacol7Layout.setHorizontalGroup(
            octavacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        octavacol7Layout.setVerticalGroup(
            octavacol7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        segundafila3.add(octavacol7);

        tablero.add(segundafila3);

        ventana.add(tablero, java.awt.BorderLayout.CENTER);

        getContentPane().add(ventana);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HuecoDer;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel LabelA;
    private javax.swing.JLabel LabelB;
    private javax.swing.JLabel LabelC;
    private javax.swing.JLabel LabelD;
    private javax.swing.JLabel LabelE;
    private javax.swing.JLabel LabelF;
    private javax.swing.JLabel LabelG;
    private javax.swing.JLabel LabelH;
    private javax.swing.JPanel bordederecho;
    private javax.swing.JPanel bordeinferior;
    private javax.swing.JPanel bordeizquierdo;
    private javax.swing.JPanel bordesuperior;
    private javax.swing.JPanel cuartacol;
    private javax.swing.JPanel cuartacol1;
    private javax.swing.JPanel cuartacol2;
    private javax.swing.JPanel cuartacol3;
    private javax.swing.JPanel cuartacol4;
    private javax.swing.JPanel cuartacol5;
    private javax.swing.JPanel cuartacol6;
    private javax.swing.JPanel cuartacol7;
    private javax.swing.JLabel huecoIzq;
    private javax.swing.JPanel octavacol;
    private javax.swing.JPanel octavacol1;
    private javax.swing.JPanel octavacol2;
    private javax.swing.JPanel octavacol3;
    private javax.swing.JPanel octavacol4;
    private javax.swing.JPanel octavacol5;
    private javax.swing.JPanel octavacol6;
    private javax.swing.JPanel octavacol7;
    private javax.swing.JPanel primeracol;
    private javax.swing.JPanel primeracol1;
    private javax.swing.JPanel primeracol2;
    private javax.swing.JPanel primeracol3;
    private javax.swing.JPanel primeracol4;
    private javax.swing.JPanel primeracol5;
    private javax.swing.JPanel primeracol6;
    private javax.swing.JPanel primeracol7;
    private javax.swing.JPanel primerafila;
    private javax.swing.JPanel primerafila1;
    private javax.swing.JPanel primerafila2;
    private javax.swing.JPanel primerafila3;
    private javax.swing.JPanel quintacol;
    private javax.swing.JPanel quintacol1;
    private javax.swing.JPanel quintacol2;
    private javax.swing.JPanel quintacol3;
    private javax.swing.JPanel quintacol4;
    private javax.swing.JPanel quintacol5;
    private javax.swing.JPanel quintacol6;
    private javax.swing.JPanel quintacol7;
    private javax.swing.JPanel segundacol;
    private javax.swing.JPanel segundacol1;
    private javax.swing.JPanel segundacol2;
    private javax.swing.JPanel segundacol3;
    private javax.swing.JPanel segundacol4;
    private javax.swing.JPanel segundacol5;
    private javax.swing.JPanel segundacol6;
    private javax.swing.JPanel segundacol7;
    private javax.swing.JPanel segundafila;
    private javax.swing.JPanel segundafila1;
    private javax.swing.JPanel segundafila2;
    private javax.swing.JPanel segundafila3;
    private javax.swing.JPanel septimacol;
    private javax.swing.JPanel septimacol1;
    private javax.swing.JPanel septimacol2;
    private javax.swing.JPanel septimacol3;
    private javax.swing.JPanel septimacol4;
    private javax.swing.JPanel septimacol5;
    private javax.swing.JPanel septimacol6;
    private javax.swing.JPanel septimacol7;
    private javax.swing.JPanel sextacol;
    private javax.swing.JPanel sextacol1;
    private javax.swing.JPanel sextacol2;
    private javax.swing.JPanel sextacol3;
    private javax.swing.JPanel sextacol4;
    private javax.swing.JPanel sextacol5;
    private javax.swing.JPanel sextacol6;
    private javax.swing.JPanel sextacol7;
    private javax.swing.JPanel tablero;
    private javax.swing.JPanel tercercol;
    private javax.swing.JPanel tercercol1;
    private javax.swing.JPanel tercercol2;
    private javax.swing.JPanel tercercol3;
    private javax.swing.JPanel tercercol4;
    private javax.swing.JPanel tercercol5;
    private javax.swing.JPanel tercercol6;
    private javax.swing.JPanel tercercol7;
    private javax.swing.JPanel ventana;
    // End of variables declaration//GEN-END:variables
}
