/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Piezas;

import static ajedrez.Tablero.COLUMNAS;
import static ajedrez.Tablero.FILAS;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author javie
 */
public class Peon extends javax.swing.JPanel implements Figuras{

    private static final int TAM_COORDENADAS = 2;
    private int[] coordenadas;
    private boolean blanco=true;
    private boolean inicio=true;
    
    private static Figuras[][] tablero;
    private static JPanel[][] tableroInterfaz;
    /**
     * Creates new form Peon
     */
    public Peon() {
        initComponents();
        coordenadas = new int[TAM_COORDENADAS];
        tablero = new Figuras[FILAS][COLUMNAS];
        tableroInterfaz = new JPanel[FILAS][COLUMNAS];
    }
    
    public void setTableros(Figuras[][] tablero,JPanel[][] tableroInterfaz){
        this.tablero=tablero;
        this.tableroInterfaz=tableroInterfaz;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icono = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(40, 40));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(40, 40));
        setLayout(new java.awt.GridLayout(1, 0));

        icono.setBackground(new java.awt.Color(255, 255, 255));
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFiguras/peonNegro.png"))); // NOI18N
        icono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconoActionPerformed(evt);
            }
        });
        add(icono);
    }// </editor-fold>//GEN-END:initComponents

    private void iconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconoActionPerformed
        moverFigura();
    }//GEN-LAST:event_iconoActionPerformed

    @Override
    public int[] moverFigura() {
       int desplazamiento=1;
       int filaant=coordenadas[0];
       int col=coordenadas[1];
       if(inicio){
           desplazamiento=2;
       }
       
       if(blanco){
           coordenadas[0]=filaant-desplazamiento;
       }else{
           coordenadas[0]=filaant+desplazamiento;
       }
       
       int fila=coordenadas[0];
       tableroInterfaz[filaant][col].remove(this);
       tableroInterfaz[filaant][col].repaint();
       tableroInterfaz[fila][col].add(this);
       
       tablero[fila][col]=tablero[filaant][col];
       tablero[filaant][col]=null;
       inicio=false;
       return coordenadas;
    }
    
    @Override
    public int[] comer() {
         return coordenadas;
    }
    
    public void setCoordenadas(int fila,int columna){
        this.coordenadas[0]=fila;
        this.coordenadas[1]=columna;
    }
    
    public void setIcono(ImageIcon icon){
        icono.setIcon(icon);
    }
    
    public void setColor(boolean blanco){
        this.blanco=blanco;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton icono;
    // End of variables declaration//GEN-END:variables

    
}
