/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Piezas;

import javax.swing.ImageIcon;


/**
 *
 * @author javie
 */
public class Peon extends javax.swing.JPanel implements Figuras{

    public static final int TAM_COORDENADAS = 2;
    private int[] coordenadas;
    /**
     * Creates new form Peon
     */
    public Peon() {
        initComponents();
        coordenadas = new int[TAM_COORDENADAS];
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icono = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(40, 40));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(40, 40));
        setLayout(new java.awt.GridLayout(1, 0));

        icono.setBackground(new java.awt.Color(255, 255, 255));
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFiguras/peonNegro.png"))); // NOI18N
        icono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconoActionPerformed(evt);
            }
        });
        add(icono);
    }// </editor-fold>//GEN-END:initComponents

    private void iconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoActionPerformed

    @Override
    public int[] moverFigura() {
       return coordenadas;
    }

    public void setIcono(ImageIcon icon){
        icono.setIcon(icon);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton icono;
    // End of variables declaration//GEN-END:variables
}
