/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Piezas;


/**
 *
 * @author javie
 */
public class Peon extends javax.swing.JPanel implements Figuras{

    public static final int TAM_COORDENADAS = 2;
    private int[] coordenadas;
    /**
     * Creates new form Peon
     */
    public Peon() {
        initComponents();
        coordenadas = new int[TAM_COORDENADAS];
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(40, 40));
        setPreferredSize(new java.awt.Dimension(40, 40));
        setLayout(new java.awt.GridLayout(1, 0));

        Titulo.setText("P");
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });
        add(Titulo);
    }// </editor-fold>//GEN-END:initComponents

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    @Override
    public int[] moverFigura() {
       return coordenadas;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Titulo;
    // End of variables declaration//GEN-END:variables
}
