/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ajedrez;

import Piezas.Figuras;
import javax.swing.JPanel;

/**
 *
 * @author javie
 */
public class Tablero extends javax.swing.JPanel {

   public static final int FILAS = 8;
   public static final int COLUMNAS = 8;
   private Figuras[][] tablero;
   private JPanel[][] tableroInterfaz;
   
   
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        tablero = new Figuras[FILAS][COLUMNAS];
        tableroInterfaz = new JPanel[FILAS][COLUMNAS];
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fila = new javax.swing.JPanel();
        col1 = new javax.swing.JPanel();
        col2 = new javax.swing.JPanel();
        col3 = new javax.swing.JPanel();
        col4 = new javax.swing.JPanel();
        col5 = new javax.swing.JPanel();
        col6 = new javax.swing.JPanel();
        col7 = new javax.swing.JPanel();
        col8 = new javax.swing.JPanel();
        fila1 = new javax.swing.JPanel();
        col9 = new javax.swing.JPanel();
        peonNegro1 = new Piezas.Peon();
        col10 = new javax.swing.JPanel();
        peonNegro2 = new Piezas.Peon();
        col11 = new javax.swing.JPanel();
        col12 = new javax.swing.JPanel();
        col13 = new javax.swing.JPanel();
        col14 = new javax.swing.JPanel();
        col15 = new javax.swing.JPanel();
        col16 = new javax.swing.JPanel();
        fila2 = new javax.swing.JPanel();
        col17 = new javax.swing.JPanel();
        col18 = new javax.swing.JPanel();
        col19 = new javax.swing.JPanel();
        col20 = new javax.swing.JPanel();
        col21 = new javax.swing.JPanel();
        col22 = new javax.swing.JPanel();
        col23 = new javax.swing.JPanel();
        col24 = new javax.swing.JPanel();
        fila3 = new javax.swing.JPanel();
        col25 = new javax.swing.JPanel();
        col26 = new javax.swing.JPanel();
        col27 = new javax.swing.JPanel();
        col28 = new javax.swing.JPanel();
        col29 = new javax.swing.JPanel();
        col30 = new javax.swing.JPanel();
        col31 = new javax.swing.JPanel();
        col32 = new javax.swing.JPanel();
        fila4 = new javax.swing.JPanel();
        col33 = new javax.swing.JPanel();
        col34 = new javax.swing.JPanel();
        col35 = new javax.swing.JPanel();
        col36 = new javax.swing.JPanel();
        col37 = new javax.swing.JPanel();
        col38 = new javax.swing.JPanel();
        col39 = new javax.swing.JPanel();
        col40 = new javax.swing.JPanel();
        fila5 = new javax.swing.JPanel();
        col41 = new javax.swing.JPanel();
        col42 = new javax.swing.JPanel();
        col43 = new javax.swing.JPanel();
        col44 = new javax.swing.JPanel();
        col45 = new javax.swing.JPanel();
        col46 = new javax.swing.JPanel();
        col47 = new javax.swing.JPanel();
        col48 = new javax.swing.JPanel();
        fila6 = new javax.swing.JPanel();
        col49 = new javax.swing.JPanel();
        col50 = new javax.swing.JPanel();
        col51 = new javax.swing.JPanel();
        col52 = new javax.swing.JPanel();
        col53 = new javax.swing.JPanel();
        col54 = new javax.swing.JPanel();
        col55 = new javax.swing.JPanel();
        col56 = new javax.swing.JPanel();
        fila7 = new javax.swing.JPanel();
        col57 = new javax.swing.JPanel();
        col58 = new javax.swing.JPanel();
        col59 = new javax.swing.JPanel();
        col60 = new javax.swing.JPanel();
        col61 = new javax.swing.JPanel();
        col62 = new javax.swing.JPanel();
        col63 = new javax.swing.JPanel();
        col64 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(8, 1));

        fila.setLayout(new java.awt.GridLayout(1, 8));

        col1.setBackground(new java.awt.Color(255, 255, 255));
        col1.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col1);

        col2.setBackground(new java.awt.Color(0, 0, 0));
        col2.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col2);

        col3.setBackground(new java.awt.Color(255, 255, 255));
        col3.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col3);

        col4.setBackground(new java.awt.Color(0, 0, 0));
        col4.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col4);

        col5.setBackground(new java.awt.Color(255, 255, 255));
        col5.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col5);

        col6.setBackground(new java.awt.Color(0, 0, 0));
        col6.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col6);

        col7.setBackground(new java.awt.Color(255, 255, 255));
        col7.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col7);

        col8.setBackground(new java.awt.Color(0, 0, 0));
        col8.setMinimumSize(new java.awt.Dimension(50, 50));
        fila.add(col8);

        add(fila);

        fila1.setLayout(new java.awt.GridLayout(1, 8));

        col9.setBackground(new java.awt.Color(0, 0, 0));
        col9.setMinimumSize(new java.awt.Dimension(50, 50));
        col9.add(peonNegro1);

        fila1.add(col9);

        col10.setBackground(new java.awt.Color(255, 255, 255));
        col10.setMinimumSize(new java.awt.Dimension(50, 50));
        col10.add(peonNegro2);

        fila1.add(col10);

        col11.setBackground(new java.awt.Color(0, 0, 0));
        col11.setMinimumSize(new java.awt.Dimension(50, 50));
        fila1.add(col11);

        col12.setBackground(new java.awt.Color(255, 255, 255));
        col12.setMinimumSize(new java.awt.Dimension(50, 50));
        fila1.add(col12);

        col13.setBackground(new java.awt.Color(0, 0, 0));
        col13.setMinimumSize(new java.awt.Dimension(50, 50));
        fila1.add(col13);

        col14.setBackground(new java.awt.Color(255, 255, 255));
        col14.setMinimumSize(new java.awt.Dimension(50, 50));
        fila1.add(col14);

        col15.setBackground(new java.awt.Color(0, 0, 0));
        col15.setMinimumSize(new java.awt.Dimension(50, 50));
        fila1.add(col15);

        col16.setBackground(new java.awt.Color(255, 255, 255));
        col16.setMinimumSize(new java.awt.Dimension(50, 50));
        fila1.add(col16);

        add(fila1);

        fila2.setLayout(new java.awt.GridLayout(1, 8));

        col17.setBackground(new java.awt.Color(255, 255, 255));
        col17.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col17);

        col18.setBackground(new java.awt.Color(0, 0, 0));
        col18.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col18);

        col19.setBackground(new java.awt.Color(255, 255, 255));
        col19.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col19);

        col20.setBackground(new java.awt.Color(0, 0, 0));
        col20.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col20);

        col21.setBackground(new java.awt.Color(255, 255, 255));
        col21.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col21);

        col22.setBackground(new java.awt.Color(0, 0, 0));
        col22.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col22);

        col23.setBackground(new java.awt.Color(255, 255, 255));
        col23.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col23);

        col24.setBackground(new java.awt.Color(0, 0, 0));
        col24.setMinimumSize(new java.awt.Dimension(50, 50));
        fila2.add(col24);

        add(fila2);

        fila3.setMinimumSize(new java.awt.Dimension(50, 50));
        fila3.setLayout(new java.awt.GridLayout(1, 8));

        col25.setBackground(new java.awt.Color(0, 0, 0));
        fila3.add(col25);

        col26.setBackground(new java.awt.Color(255, 255, 255));
        fila3.add(col26);

        col27.setBackground(new java.awt.Color(0, 0, 0));
        fila3.add(col27);

        col28.setBackground(new java.awt.Color(255, 255, 255));
        fila3.add(col28);

        col29.setBackground(new java.awt.Color(0, 0, 0));
        fila3.add(col29);

        col30.setBackground(new java.awt.Color(255, 255, 255));
        fila3.add(col30);

        col31.setBackground(new java.awt.Color(0, 0, 0));
        fila3.add(col31);

        col32.setBackground(new java.awt.Color(255, 255, 255));
        fila3.add(col32);

        add(fila3);

        fila4.setLayout(new java.awt.GridLayout(1, 8));

        col33.setBackground(new java.awt.Color(255, 255, 255));
        col33.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col33);

        col34.setBackground(new java.awt.Color(0, 0, 0));
        col34.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col34);

        col35.setBackground(new java.awt.Color(255, 255, 255));
        col35.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col35);

        col36.setBackground(new java.awt.Color(0, 0, 0));
        col36.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col36);

        col37.setBackground(new java.awt.Color(255, 255, 255));
        col37.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col37);

        col38.setBackground(new java.awt.Color(0, 0, 0));
        col38.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col38);

        col39.setBackground(new java.awt.Color(255, 255, 255));
        col39.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col39);

        col40.setBackground(new java.awt.Color(0, 0, 0));
        col40.setMinimumSize(new java.awt.Dimension(50, 50));
        fila4.add(col40);

        add(fila4);

        fila5.setLayout(new java.awt.GridLayout(1, 8));

        col41.setBackground(new java.awt.Color(0, 0, 0));
        col41.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col41);

        col42.setBackground(new java.awt.Color(255, 255, 255));
        col42.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col42);

        col43.setBackground(new java.awt.Color(0, 0, 0));
        col43.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col43);

        col44.setBackground(new java.awt.Color(255, 255, 255));
        col44.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col44);

        col45.setBackground(new java.awt.Color(0, 0, 0));
        col45.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col45);

        col46.setBackground(new java.awt.Color(255, 255, 255));
        col46.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col46);

        col47.setBackground(new java.awt.Color(0, 0, 0));
        col47.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col47);

        col48.setBackground(new java.awt.Color(255, 255, 255));
        col48.setMinimumSize(new java.awt.Dimension(50, 50));
        fila5.add(col48);

        add(fila5);

        fila6.setLayout(new java.awt.GridLayout(1, 8));

        col49.setBackground(new java.awt.Color(255, 255, 255));
        col49.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col49);

        col50.setBackground(new java.awt.Color(0, 0, 0));
        col50.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col50);

        col51.setBackground(new java.awt.Color(255, 255, 255));
        col51.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col51);

        col52.setBackground(new java.awt.Color(0, 0, 0));
        col52.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col52);

        col53.setBackground(new java.awt.Color(255, 255, 255));
        col53.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col53);

        col54.setBackground(new java.awt.Color(0, 0, 0));
        col54.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col54);

        col55.setBackground(new java.awt.Color(255, 255, 255));
        col55.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col55);

        col56.setBackground(new java.awt.Color(0, 0, 0));
        col56.setMinimumSize(new java.awt.Dimension(50, 50));
        fila6.add(col56);

        add(fila6);

        fila7.setLayout(new java.awt.GridLayout(1, 8));

        col57.setBackground(new java.awt.Color(0, 0, 0));
        col57.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col57);

        col58.setBackground(new java.awt.Color(255, 255, 255));
        col58.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col58);

        col59.setBackground(new java.awt.Color(0, 0, 0));
        col59.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col59);

        col60.setBackground(new java.awt.Color(255, 255, 255));
        col60.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col60);

        col61.setBackground(new java.awt.Color(0, 0, 0));
        col61.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col61);

        col62.setBackground(new java.awt.Color(255, 255, 255));
        col62.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col62);

        col63.setBackground(new java.awt.Color(0, 0, 0));
        col63.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col63);

        col64.setBackground(new java.awt.Color(255, 255, 255));
        col64.setMinimumSize(new java.awt.Dimension(50, 50));
        fila7.add(col64);

        add(fila7);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel col1;
    private javax.swing.JPanel col10;
    private javax.swing.JPanel col11;
    private javax.swing.JPanel col12;
    private javax.swing.JPanel col13;
    private javax.swing.JPanel col14;
    private javax.swing.JPanel col15;
    private javax.swing.JPanel col16;
    private javax.swing.JPanel col17;
    private javax.swing.JPanel col18;
    private javax.swing.JPanel col19;
    private javax.swing.JPanel col2;
    private javax.swing.JPanel col20;
    private javax.swing.JPanel col21;
    private javax.swing.JPanel col22;
    private javax.swing.JPanel col23;
    private javax.swing.JPanel col24;
    private javax.swing.JPanel col25;
    private javax.swing.JPanel col26;
    private javax.swing.JPanel col27;
    private javax.swing.JPanel col28;
    private javax.swing.JPanel col29;
    private javax.swing.JPanel col3;
    private javax.swing.JPanel col30;
    private javax.swing.JPanel col31;
    private javax.swing.JPanel col32;
    private javax.swing.JPanel col33;
    private javax.swing.JPanel col34;
    private javax.swing.JPanel col35;
    private javax.swing.JPanel col36;
    private javax.swing.JPanel col37;
    private javax.swing.JPanel col38;
    private javax.swing.JPanel col39;
    private javax.swing.JPanel col4;
    private javax.swing.JPanel col40;
    private javax.swing.JPanel col41;
    private javax.swing.JPanel col42;
    private javax.swing.JPanel col43;
    private javax.swing.JPanel col44;
    private javax.swing.JPanel col45;
    private javax.swing.JPanel col46;
    private javax.swing.JPanel col47;
    private javax.swing.JPanel col48;
    private javax.swing.JPanel col49;
    private javax.swing.JPanel col5;
    private javax.swing.JPanel col50;
    private javax.swing.JPanel col51;
    private javax.swing.JPanel col52;
    private javax.swing.JPanel col53;
    private javax.swing.JPanel col54;
    private javax.swing.JPanel col55;
    private javax.swing.JPanel col56;
    private javax.swing.JPanel col57;
    private javax.swing.JPanel col58;
    private javax.swing.JPanel col59;
    private javax.swing.JPanel col6;
    private javax.swing.JPanel col60;
    private javax.swing.JPanel col61;
    private javax.swing.JPanel col62;
    private javax.swing.JPanel col63;
    private javax.swing.JPanel col64;
    private javax.swing.JPanel col7;
    private javax.swing.JPanel col8;
    private javax.swing.JPanel col9;
    private javax.swing.JPanel fila;
    private javax.swing.JPanel fila1;
    private javax.swing.JPanel fila2;
    private javax.swing.JPanel fila3;
    private javax.swing.JPanel fila4;
    private javax.swing.JPanel fila5;
    private javax.swing.JPanel fila6;
    private javax.swing.JPanel fila7;
    private Piezas.Peon peonNegro1;
    private Piezas.Peon peonNegro2;
    // End of variables declaration//GEN-END:variables
}
