/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ajedrez;

import Piezas.Figuras;
import Piezas.Peon;
import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author javie
 */
public class Tablero extends javax.swing.JPanel {

   public static final int FILAS = 8;
   public static final int COLUMNAS = 8;
   private Figuras[][] tablero;
   private JPanel[][] tableroInterfaz;
   
   
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        tablero = new Figuras[FILAS][COLUMNAS];
        tableroInterfaz = new JPanel[FILAS][COLUMNAS];
        inicializarTableroInterfaz();
        inicializarTablero();
        
    }

    private void InicializarFilaPeon(int fila, ImageIcon icon){
        for(int col=0;col<COLUMNAS;col++){
            Peon peon=new Peon();
            peon.setIcono(icon);
            tablero[fila][col]=peon;
            tableroInterfaz[fila][col].add(peon);
        }
    }
    
    private void inicializarTablero(){
        ImageIcon iconPeonBlanco=new ImageIcon(getClass().getResource("/ImagenesFiguras/peonBlanco.png"));
        ImageIcon iconPeonNegro=new ImageIcon(getClass().getResource("/ImagenesFiguras/peonNegro.png"));
        InicializarFilaPeon(1,iconPeonNegro);
        InicializarFilaPeon(6,iconPeonBlanco);
        
       
    }
    
    private void inicializarTableroInterfaz(){
        //Color de las casillas del tablero;
        Color casillaBlanca=Color.WHITE;
        Color casillaNegra=Color.BLACK;
        
        for(int fila=0;fila<FILAS;fila++){
            for(int col=0;col<COLUMNAS;col++){
                JPanel casilla=new JPanel();
                casilla.setBackground((fila + col) % 2 == 0 ? casillaBlanca : casillaNegra);
                this.add(casilla);
                tableroInterfaz[fila][col]=casilla;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(8, 8));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
